# .github/workflows/adhoc-build.yml

name: AdHoc Mobile Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Build Branch"
        required: true
        default: "develop"
      environment:
        description: "Select environment (staging or live)"
        required: true
        default: "staging"

jobs:
  ios-adhoc:
    name: iOS AdHoc Build
    runs-on: macos-latest
    steps:
      # Checkout this config repository
      - name: Checkout CI config
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Checkout the actual application code
      - name: Checkout real code
        run: |
          git clone --branch ${{ github.event.inputs.branch }} --single-branch \
            ${{ secrets.PRIVATE_REPO_FULL_NAME }} real-code

      # Install JS dependencies
      - name: Install JS dependencies
        run: yarn --cwd real-code install --frozen-lockfile

      # Set up Ruby and Fastlane
      - name: Setup Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.x"
      - name: Install Bundler
        run: |
          cd real-code
          gem install bundler
          bundle install

      # Install CocoaPods dependencies
      - name: iOS Pod install
        working-directory: real-code/ios
        run: bundle exec pod install --repo-update

      # Build and upload AdHoc via Fastlane
      - name: Build & AdHoc via Fastlane
        working-directory: real-code
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          BUNDLE_ID_STAGING: ${{ secrets.BUNDLE_ID_STAGING }}
          BUNDLE_ID_LIVE: ${{ secrets.BUNDLE_ID_LIVE }}
          DIAWI_API_TOKEN: ${{ secrets.DIAWI_API_TOKEN }}
          GDRIVE_FOLDER_STAGING_ID: ${{ secrets.GDRIVE_FOLDER_STAGING_ID }}
          GDRIVE_FOLDER_LIVE_ID: ${{ secrets.GDRIVE_FOLDER_LIVE_ID }}
        run: bundle exec fastlane ios adhoc env:${{ github.event.inputs.environment }}

      # Upload IPA artifact for debugging/storage
      # - name: Upload IPA artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ios-ipa
      #     path: real-code/ios/build/*.ipa

  # android-adhoc:
  #   name: Android AdHoc Build 
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout this config repository
  #     - name: Checkout CI config
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1

  #     # Checkout the actual application code
  #     - name: Checkout real code
  #       run: |
  #         git clone --branch ${{ github.event.inputs.branch }} --single-branch \
  #           ${{ secrets.PRIVATE_REPO_SSH_URL }} real-code

  #     # Install JS dependencies
  #     - name: Install JS dependencies
  #       run: yarn --cwd real-code install --frozen-lockfile

  #     # Set up Ruby and Fastlane
  #     - name: Setup Ruby & Fastlane
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: "3.x"
  #     - name: Install Bundler
  #       run: |
  #         cd real-code
  #         gem install bundler
  #         bundle install

  #     # Build and upload AdHoc via Fastlane
  #     - name: Build & AdHoc via Fastlane
  #       working-directory: real-code
  #       env:
  #         FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  #         TEAM_ID: ${{ secrets.TEAM_ID }}
  #         BUNDLE_ID_STAGING: ${{ secrets.BUNDLE_ID_STAGING }}
  #         BUNDLE_ID_LIVE: ${{ secrets.BUNDLE_ID_LIVE }}
  #         DIAWI_API_TOKEN: ${{ secrets.DIAWI_API_TOKEN }}
  #         GDRIVE_FOLDER_STAGING_ID: ${{ secrets.GDRIVE_FOLDER_STAGING_ID }}
  #         GDRIVE_FOLDER_LIVE_ID: ${{ secrets.GDRIVE_FOLDER_LIVE_ID }}
  #       run: bundle exec fastlane android adhoc env:${{ github.event.inputs.environment }}

      # Upload APK artifact for debugging/storage
      # - name: Upload APK artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: android-apk
      #     path: real-code/android/app/build/outputs/apk/**/*.apk
