name: Build and upload apk & ipa for internal test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Build Branch"
        required: true
        default: "develop"
      environment:
        description: "Select environment (staging or live)"
        required: true
        default: "staging"

jobs:
  ios-adhoc:
    uses: ./.github/actions/ios/adhoc-build
    with:
      branch: ${{ inputs.branch }}
      environment: ${{ inputs.environment }}

  android-apk:
    uses: ./.github/actions/android/apk-build
    with:
      branch: ${{ inputs.branch }}
      environment: ${{ inputs.environment }}
