name: Build and upload apk & ipa for internal test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Build Branch"
        required: true
        default: "develop"
      environment:
        description: "Select environment (staging or live)"
        required: true
        default: "staging"

jobs:
  ios-adhoc:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run iOS AdHoc composite action
        uses: ./.github/actions/ios/adhoc-build
        with:
          branch: ${{ inputs.branch }}
          environment: ${{ inputs.environment }}

  android-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Android APK composite action
        uses: ./.github/actions/android/apk-build
        with:
          branch: ${{ inputs.branch }}
          environment: ${{ inputs.environment }}
